In [109]:
import numpy as np

In [110]:
a = np.arange (3)

In [111]:
a

array([0, 1, 2])

In [112]:
b = 5

In [113]:
b

5

In [114]:
c = a+b

In [115]:
c

array([5, 6, 7])

In [116]:
c.shape

(3,)

In [117]:
a = np.ones((3,3))

In [118]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [119]:
a.shape

(3, 3)

In [120]:
b = np.arange (3)

In [121]:
b

array([0, 1, 2])

In [122]:
b.shape

(3,)

In [123]:
c= a+b

In [124]:
c

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [125]:
c.shape

(3, 3)

In [126]:
a = np.arange(3)

In [127]:
a

array([0, 1, 2])

In [128]:
a.shape

(3,)

In [129]:
a.reshape ((3,1))

array([[0],
       [1],
       [2]])

In [130]:
a.shape

(3,)

In [131]:
b = np.arange(3)

In [132]:
b

array([0, 1, 2])

In [133]:
b.shape

(3,)

In [134]:
c = a+b

In [135]:
c

array([0, 2, 4])

In [136]:
a = np.ones ((2,3))+2

In [137]:
a

array([[3., 3., 3.],
       [3., 3., 3.]])

In [138]:
b = np.ones ((3,2))+2

In [139]:
b

array([[3., 3.],
       [3., 3.],
       [3., 3.]])

In [140]:
c = np.dot(a,b)

In [141]:
c

array([[27., 27.],
       [27., 27.]])

In [142]:
c.shape

(2, 2)

In [143]:
c = a@b

In [144]:
c

array([[27., 27.],
       [27., 27.]])

In [145]:
c.shape

(2, 2)

Apakah proses pertambahan bisa dilakukan untuk objek NumPy dengan dimensi 2x3 dan 3x2 ?

Tidak bisa, Operasi aritmatika dasar (seperti +, -, *, /) antar array di NumPy menggunakan aturan yang disebut Broadcasting. Agar dua matriks bisa ditambahkan, dimensinya harus sama persis, atau memenuhi aturan broadcasting (dimensi harus cocok dari ujung kanan/belakang, dan jika berbeda, salah satunya harus bernilai 1).

Karena matriks (2, 3) dan (3, 2) memiliki ukuran yang saling terbalik dan tidak ada dimensi yang bernilai 1 untuk di-broadcast, NumPy tidak akan tahu elemen mana yang harus ditambahkan dengan mana. Jika kamu mencobanya (a + b), Python akan mengeluarkan pesan error: ValueError: operands could not be broadcast together.

Apakah proses perkalian bisa dilakukan untuk objek NumPy dengan dimensi 2x3 dan 3x2 ?

Tergantung, Operasi aritmatika dasar (seperti +, -, *, /) antar array di NumPy menggunakan aturan yang disebut Broadcasting. Agar dua matriks bisa ditambahkan, dimensinya harus sama persis, atau memenuhi aturan broadcasting (dimensi harus cocok dari ujung kanan/belakang, dan jika berbeda, salah satunya harus bernilai 1).

Karena matriks (2, 3) dan (3, 2) memiliki ukuran yang saling terbalik dan tidak ada dimensi yang bernilai 1 untuk di-broadcast, NumPy tidak akan tahu elemen mana yang harus ditambahkan dengan mana. Jika kamu mencobanya (a + b), Python akan mengeluarkan pesan error: ValueError: operands could not be broadcast together.